version: "3.8"
services:
  database:
    image: mongo
    volumes:
      - "./db:/data/db"
  broker:
    image: nats
  proxy:
    image: envoyproxy/envoy-alpine
    volumes:
      - ./etc:/etc/midas
  express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    ports:
      - 8081:8081
    depends_on:
      - database
  historical:
    build:
      context: ./backend
      dockerfile: devel.dockerfile
      args:
        - SERVICE=historical
    command:
      - -c
      - /etc/midas/midas.yml
    volumes:
      - ./etc:/etc/midas
      - ./backend:/opt/code
    depends_on:
      - database
      - broker
  symbol:
    build:
      context: ./backend
      dockerfile: devel.dockerfile
      args:
        - SERVICE=symbol
    command:
      - -c
      - /etc/midas/midas.yml
    volumes:
      - ./etc:/etc/midas
      - ./backend:/opt/code
    depends_on:
      - database
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/opt/code
      - /opt/code/node_modules
    ports:
      - 8000:4200
