version: "3.8"
services:
  database:
    image: mongo
    volumes:
      - "./db:/data/db"
  express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    ports:
      - 8081:8081
    depends_on:
      - database
  testbed-binance:
    build:
      context: .
      dockerfile: devel.dockerfile
      args:
        - SERVICE=testbeds
    volumes:
      - ./backend:/opt/code
    command:
      - run
      - -e binance
      - -n tcp
      - -a :5000
      - -d mongodb://database
    depends_on:
      - database
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/opt/code
      - /opt/code/node_modules
    ports:
      - 8000:4200
