version: "3.8"
services:
  database:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: midas
    volumes:
      - "./db:/data/db"
      - "./etc/mongo/scripts:/docker-entrypoint-initdb.d"
  broker:
    image: nats
  proxy:
    image: envoyproxy/envoy-alpine:v1.15-latest
    command:
      - -c
      - /etc/midas/envoy.yaml
    volumes:
      - ./etc:/etc/midas
    environment:
      ENVOY_UID: 0
    depends_on:
      - symbol
      - historical
      - frontend
    ports:
      - 50000:50000
      - 50001:50001
  express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    ports:
      - 8081:8081
    depends_on:
      - database
  historical:
    build:
      context: ./backend
      dockerfile: devel.dockerfile
      args:
        - SERVICE=historical
    command:
      - -c
      - /etc/midas/midas.yml
    volumes:
      - ./etc:/etc/midas
      - ./backend:/opt/code
    depends_on:
      - database
      - broker
  symbol:
    build:
      context: ./backend
      dockerfile: devel.dockerfile
      args:
        - SERVICE=symbol
    command:
      - -c
      - /etc/midas/midas.yml
    volumes:
      - ./etc:/etc/midas
      - ./backend:/opt/code
    depends_on:
      - database
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/opt/code
      - /opt/code/node_modules
