apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: midas
build:
  artifacts:
    - image: frontend
      context: frontend
      hooks:
        before:
          - command: [pnpm, run, build]
            os: [windows, darwin, linux]
            dir: ./frontend
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
deploy:
  kustomize:
    paths:
      - ./k8s
    hooks:
      after:
        - host:
            command: [./gen.sh]
            os: [darwin, linux]
            dir: ./k8s/tls
        - host:
            command: [./upload-proxy-cert.sh]
            os: [darwin, linux]
            dir: ./k8s/tls
