apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: midas
build:
  artifacts:
    - image: frontend
      context: frontend
      docker: {}
      hooks:
        before:
          - command: [pnpm, run, build]
            os: [darwin, linux]
            dir: ./frontend
    - image: historical-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: historical_service
    - image: historical-fetch-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: historical_fetch_worker
deploy:
  kustomize:
    paths:
      - ./k8s
    hooks:
      before:
        - host:
            command: [./gen.sh]
            os: [darwin, linux]
            dir: ./k8s/tls
