apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: midas
build:
  artifacts:
    - image: frontend
      context: frontend
      docker: {}
      hooks:
        before:
          - command: [pnpm, run, build]
            os: [darwin, linux]
            dir: ./frontend
    - image: historical-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: historical_service
    - image: historical-fetch-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: historical_fetch_worker
    - image: historical-date-split-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: historical_date_splitter
    - image: symbol-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: symbol_service
    - image: trade-observer-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: trade_observer_worker
    - image: notify-worker
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: notify_worker
    - image: trade-observer-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: trade_observer_service
    - image: token-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: token_service
    - image: keychain-service
      context: backend
      docker:
        dockerfile: devel.dockerfile
        buildArgs:
          SERVICE: keychain_service
    - image: transpiler-service
      context: backend
      docker:
        dockerfile: nodejs.dockerfile
        buildArgs:
          CODE_PATH: services/transpiler
deploy:
  kustomize:
    paths:
      - ./k8s
    hooks:
      before:
        - host:
            command: [./gen.sh]
            os: [darwin, linux]
            dir: ./k8s/tls
