[package]
name = "bot_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bot = { path = "../../libs/bot" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
errors = { path = "../../libs/errors" }

warp = { version = "0.3.1", features = ["tls"] }
mongodb = { version = "1.2.1", default-features = false, features = ["async-std-runtime"] }
reqwest = { version = "0.11.4", features = ["gzip", "brotli", "json", "rustls-tls", "cookies"] }
