[package]
name = "bot_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bot = { path = "../../libs/bot" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
errors = { path = "../../libs/errors" }
csrf = { path = "../../libs/csrf" }
access_logger = { path = "../../libs/access_logger" }

warp = { version = "0.3.2", features = ["tls"] }
mongodb = { version = "2.2.1", default-features = false, features = ["async-std-runtime"] }
reqwest = { version = "0.11.10", features = ["gzip", "brotli", "json", "rustls-tls", "cookies"] }
tokio = { version = "1.18.2", features = ["macros", "rt", "rt-multi-thread", "signal"] }
futures = "0.3.21"
slog = "2.7.0"
clap = { version = "3.1.18", features = ["derive"] }
libc = "0.2.126"
