apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databasePVC
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 100Gi
  storageClassName: local
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
