[workspace]
members = [
  "libs/errors",
  "libs/writers",
  "libs/rulesets/executor",
  "libs/rulesets/sign",
  "libs/rulesets/symbol_fetcher",
  "libs/rulesets/symbol_recorder",
  "libs/rulesets/trade_observer",

  "libs/entities",
  "libs/csrf",
  "libs/errors",
  "libs/keychain",
  "libs/config",
  "libs/slog_builder",
  "libs/rpc",
  "libs/types",
  "libs/subscribe",
  "libs/date_splitter",
  "libs/bot",

  "libs/exchanges/executors",
  "libs/exchanges/history",
  "libs/exchanges/observers",
  "libs/exchanges/symbols",
  "libs/exchanges/notification",
  "libs/exchanges/clients",

  "services/historical",
  "services/symbol",
  "services/observer",
  "services/token",
  "services/keychain",
  "services/bot",

  "workers/historical",
  "workers/observer",
  "workers/notify"
]
