[workspace]
members = [
  "libs/config",
  "libs/exchanges",
  "libs/slog_builder",
  "libs/rpc",
  "libs/types",
  # "libs/tls",

  "services/historical",
  "services/symbol",
  "services/observer",

  "workers/historical",
  "workers/observer"
]
