[workspace]
members = [
  "libs/errors",
  "libs/rulesets/entities",
  "libs/rulesets/base_recorder",
  "libs/rulesets/executor",
  "libs/rulesets/sign",
  "libs/rulesets/symbol_fetcher",
  "libs/rulesets/symbol_recorder",
  "libs/rulesets/trade_observer",
  "libs/rulesets/notification",
  "libs/rulesets/history",

  "libs/csrf",
  "libs/errors",
  "libs/keychain",
  "libs/config",
  "libs/slog_builder",
  "libs/rpc",
  "libs/types",
  "libs/subscribe",
  "libs/date_splitter",

  "libs/exchanges/binance/executors",
  "libs/exchanges/binance/histories",
  "libs/exchanges/binance/observers",
  "libs/exchanges/binance/symbols",
  "libs/exchanges/binance/notification",
  "libs/exchanges/binance/clients",

  "services/historical",
  "services/symbol",
  "services/observer",
  "services/token",
  "services/keychain",

  "workers/historical",
  "workers/observer",
  "workers/notify"
]
