[workspace]
members = [
  "libs/csrf",
  "libs/config",
  "libs/exchanges",
  "libs/slog_builder",
  "libs/rpc",
  "libs/types",

  "services/historical",
  "services/symbol",
  "services/observer",
  "services/token",
  "services/keychain",

  "workers/historical",
  "workers/observer",
  "workers/notify"
]
