[profile.release]
opt-level = 2
lto = true
strip = true

[workspace]
resolver = "2"
members = ["libs/exchanges/*", "libs/*", "services/*", "workers/*"]
exclude = ["libs/exchanges", "services/transpiler"]
