[workspace]
members = [
  "libs/rulesets/entities",
  "libs/rulesets/base_recorder",
  "libs/rulesets/executor",
  "libs/rulesets/history_recorder",
  "libs/rulesets/history_fetcher",
  "libs/rulesets/sign",
  "libs/rulesets/symbol_fetcher",
  "libs/rulesets/symbol_recorder",
  "libs/rulesets/trade_observer",
  "libs/rulesets/user_stream",

  "libs/csrf",
  "libs/errors",
  "libs/config",
  "libs/exchanges",
  "libs/slog_builder",
  "libs/rpc",
  "libs/types",

  "services/historical",
  "services/symbol",
  "services/observer",
  "services/token",
  "services/keychain",

  "workers/historical",
  "workers/observer",
  "workers/notify"
]
