apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: historical

resources:
  - "../template"

patches:
  - target:
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: historical

images:
  - name: template
    newName: historical_service
