openapi: 3.0.3
info:
  title: "Midas API Specification"
  version: 0.0.0
  license:
    name: "MIT"
    url: "https://mit-license.org/"
  contact:
    name: "Hiroaki Yamamoto"
    url: "https://github.com/hiroaki-yamamoto/midas"
servers:
  - url: https://localhost:50000/historical
    description: "Local Development Server"

components:
  responses:
    HistChartProg:
      description: The progress of the historical chart fetch
      content:
        application/json:
          schema:
            type: object
            properties:
              symbol:         { type: string }
              num_symbol:     { type: integer }
              cur_symbol_num: { type: integer }
              num_objects:    { type: integer }
              cur_object_num: { type: integer }

  parameters:
    exchanges:
      name: exchanges
      in: path
      required: true
      description: "The name of the exchange"
      schema:
        type: string
        enum:
          - binance
paths:
  /subscribe:
    summary: "Subscribe the progress of historical data fetching"
    get:
      summary: "Start the websocket"
      responses:
        101:
          description: "Switching the protocol to Websocket"
          content:
            application/json:
              schema:
                $ref: "#/components/responses/HistChartProg"
  /sync/{exchanges}:
    summary: "Synchronization start endpoint for historycal data fetching"
    parameters:
      - $ref: "#/components/parameters/exchanges"
    post:
      summary: "Start the synchronozation"
      responses:
        '200':
          description: "The job has been queued."
        default:
          description: "Failed to queue the job."
    delete:
      summary: "Cancel the job"
      responses:
        '200':
          description: "The job has been canceled."
        default:
          description: "Failed to cancel the job."
