[package]
name = "historical"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.2.1"
serde = {version = "1.0.112", features = ["derive"]}
rmp-serde = "0.14.3"
nats = "0.5.0"
mongodb = "1.0.0"
crossbeam = "0.7.3"
clap = "3.0.0-beta.1"
serde_yaml = "0.8.13"
tokio = {version = "0.2.21", features = ["macros", "rt-threaded"]}
slog_builder = { path = "../../libs/slog_builder" }
types = { path = "../../libs/types" }
slog = "2.5.2"
slog-atomic = "3.0.0"
prost = "0.6.1"
async-trait = "0.1.36"

[build-dependencies]
tonic-build = "0.2.0"
