[package]
name = "historical"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.2.1"
serde = "1.0.112"
rmp-serde = "0.14.3"
nats = "0.5.0"
mongodb = "1.0.0"
crossbeam = "0.7.3"
config = "0.10.1"
clap = "3.0.0-beta.1"
