[package]
name = "trade_observer_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observers = { path = "../../libs/exchanges/observers" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }

clap = { version = "4.2.1", features = ["derive"] }
tokio = { version = "1.25.0", features = ["signal", "rt", "rt-multi-thread", "macros"] }
nats = "0.24.0"
log = { version = "0.4", features = [ "kv_unstable", "kv_unstable_serde" ] }
futures = "0.3.26"
libc = "0.2.139"
mongodb = { version = "2.4.0", default-features = false, features = ["async-std-runtime"] }
