[package]
name = "trade_observer_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observers = { path = "../../libs/exchanges/observers" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }

clap = { version = "4.0.15", features = ["derive"] }
tokio = { version = "1.21.2", features = ["signal", "rt", "rt-multi-thread", "macros"] }
nats = "0.23.0"
slog = "2.7.0"
futures = "0.3.24"
libc = "0.2.135"
mongodb = { version = "2.3.1", default-features = false, features = ["async-std-runtime"] }
