apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend
        name: frontend
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
          - name: svc-cert
            mountPath: "/etc/certs/svc"
            readOnly: true
      volumes:
        - name: svc-cert
          secret:
            secretName: svc-cert
status: {}
