[build]
incremental = false
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "target-feature=+crt-static"
]

[net]
retry = 3
