[build]
incremental = false

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
CC="musl-gcc -fPIE -pie -O2"
OPENSSL_STATIC = "true"
OPENSSL_DIR = { value = "../deps/openssl", relative = true}
OPENSSL_LIB_DIR = { value = "../deps/openssl/lib64", relative = true}

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[net]
retry = 3
