version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  backend-rust:
    docker:
      - image: rust
    # working_directory: .

jobs:
  build-backend:
    executor: backend-rust
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "backend/Cargo.lock" }}
      - run:
          name: "Install musl tools"
          command: "apt-get update && apt-get install -y musl-tools"
      - run: rustup component add rustfmt
      - run:
          name: "Install musl package"
          command: "rustup target add x86_64-unknown-linux-musl"
      - run:
          name: "Extract openssl-musl package"
          command: "tar xJvf openssl-musl.txz && mv openssl-musl ~/"
          working_directory: ./.circleci
      - run:
          name: Build the package
          command: |
            export OPENSSL_DIR=${HOME}/openssl-musl/musl
            cargo build --target x86_64-unknown-linux-musl --release
          working_directory: ./backend
          environment:
            PKG_CONFIG_ALLOW_CROSS: '1'
            OPENSSL_STATIC: 'true'
      - run: ls ./backend/target/*
      - save_cache:
          paths:
            - ./backend/target
            - ~/.rustup
          key: build-cache-{{ checksum "backend/Cargo.lock" }}
      - store_artifacts:
          path: ./backend/target/x86_64-unknown-linux-musl/release/historical
          destination: historical
      - slack/status

workflows:
  version: 2
  build:
    jobs:
      - build-backend: { filters: { branches: { only: /.*/ } } }
