version: 2.1

executors:
  backend-rust:
    docker:
      - image: rust
    # working_directory: .

jobs:
  build-backend:
    executor: backend-rust
    steps:
      - checkout
      - restore_cache:
          key: build-cache
      - run:
          name: "Install musl tools"
          command: "apt-get update && apt-get install -y musl-tools"
      - run:
          name: "Install musl package"
          command: "rustup target add x86_64-unknown-linux-musl"
      - run:
          name: "Extract openssl-musl package"
          command: "tar xJvf openssl-musl.txz"
          working_directory: ./.circleci
      - run:
          name: Build the package
          command: cargo build --target x86_64-unknown-linux-musl --release
          working_directory: ./backend
          environment:
            PKG_CONFIG_ALLOW_CROSS: '1'
            OPENSSL_STATIC: 'true'
            OPENSSL_DIR: ../.circleci/openssl-musl
      - save_cache:
          paths:
            - ./target
            - ~/.rustup
          key: build-cache

workflows:
  version: 2
  build:
    jobs:
      - build-backend: { filters: { branches: { only: /.*/ } } }
