version: 2.1

orbs:
  slack: circleci/slack@4.4.2

executors:
  backend-rust:
    docker:
      - image: rust
    environment:
      SCCACHE_VER: v0.2.15
      RUSTC_WRAPPER: /usr/local/bin/sccache
  docker-build:
    docker:
      - image: docker
        environment:
          BASH_ENV: /etc/profile

jobs:
  build-backend:
    executor: backend-rust
    environment:
      PREV_REV: << pipeline.git.base_revision >>
    steps:
      - checkout
      - run:
          name: "Show prev revision"
          command: |
            echo $PREV_REV
      - restore_cache:
          key: target-cache-{{ .Branch }}-{{ checksum "backend/Cargo.lock"}}
      - restore_cache:
          key: rustup-{{ .Branch }}-{{ checksum "backend/Cargo.lock"}}
      - restore_cache:
          key: sccache-{{ .Branch }}-{{ checksum "backend/Cargo.lock"}}
      - restore_cache:
          key: cargo-{{ .Branch }}-{{ checksum "backend/Cargo.lock"}}
      - run:
          name: "Install musl tools"
          command: "apt-get update && apt-get install -y musl-tools jq curl lld"
      - run: rustup component add rustfmt
      - run:
          name: "Install musl package"
          command: "rustup target add x86_64-unknown-linux-musl"
      - run:
          name: "Install sccache"
          command: |
            TARGET="sccache-${SCCACHE_VER}-x86_64-unknown-linux-musl"
            SCCACHE_ARCHIVE="${TARGET}.tar.gz"
            SCCACHE_URL='https://github.com/mozilla/sccache/releases/download/'
            SCCACHE_URL="${SCCACHE_URL}${SCCACHE_VER}/${SCCACHE_ARCHIVE}"
            curl -fLC - ${SCCACHE_URL} -o ${SCCACHE_ARCHIVE}
            tar xzf ${SCCACHE_ARCHIVE}
            mv "${TARGET}/sccache" $RUSTC_WRAPPER
            rm -rf ${SCCACHE_ARCHIVE} ${TARGET}
            chmod u+x $RUSTC_WRAPPER
      - run:
          name: "Extract openssl-musl package"
          command: "tar xJvf openssl-musl.txz && mv openssl-musl ~/"
          working_directory: ./.circleci
      - run:
          name: Build the package
          command: |
            export \
              OPENSSL_DIR=${HOME}/openssl-musl/musl \
              OPENSSL_LIB_DIR=${HOME}/openssl-musl/musl/lib64
            cargo build --target x86_64-unknown-linux-musl --release
          working_directory: ./backend
          environment:
            PKG_CONFIG_ALLOW_CROSS: '1'
            OPENSSL_STATIC: 'true'
      - run:
          name: "Print cache request summary"
          command: sccache -s
      - save_cache:
          paths:
            - ./backend/target
          key: target-cache-{{ .Branch }}-{{ checksum "backend/Cargo.lock"}}
      - save_cache:
          paths:
            - ~/.rustup
          key: rustup-{{ .Branch }}-{{ checksum "backend/Cargo.lock"}}
      - save_cache:
          paths:
            - ~/.cache/sccache
          key: sccache-{{ .Branch }}-{{ checksum "backend/Cargo.lock"}}
      - save_cache:
          paths:
            - ~/.cargo/registry
          key: cargo-{{ .Branch }}-{{ checksum "backend/Cargo.lock"}}
      - run:
          name: "Collect executable"
          command: |
            mkdir bin
            mv \
              $(file \
                --mime-type *|\
                grep application/x-pie-executable|\
                sed -e 's@:[[:space:]]*application\/x-pie-executable@@g'\
              ) \
            bin
          working_directory:
            ./backend/target/x86_64-unknown-linux-musl/release
      - run:
          name: "List compiled files"
          command: ls -lha
          working_directory: ./backend/target/x86_64-unknown-linux-musl/release/bin
      - slack/notify:
          event: fail
          ignore_errors: false
          template: basic_fail_1
      - run:
          name: "Export slack notification on success"
          command: |
            echo 'export SLACK_TMPL_PASS=$(cat ./.circleci/slack_template_success.json)' >> $BASH_ENV
      - slack/notify:
          event: pass
          ignore_errors: false
          template: SLACK_TMPL_PASS
      - persist_to_workspace:
          root: .
          paths:
            - ./.circleci/slack_template_success.json
            - ./backend/target/x86_64-unknown-linux-musl/release/bin
            - ./backend/prod.dockerfile
  deploy-image:
    executor: docker-build
    shell: /bin/sh -leo pipefail
    parameters:
      service_name:
        type: string
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: "Install bash"
          command: |
            apk update
            apk add --no-cache bash curl jq
      - run:
          name: Log into docker.pkg.github.com
          command: |
            docker login https://docker.pkg.github.com \
              -u ${GITHUB_USERNAME} \
              -p ${GITHUB_TOKEN}
      - run:
          name: Build Docker Image
          command: |
            docker build \
              -f prod.dockerfile \
              --build-arg SERVICE=<<parameters.service_name>> \
              -t docker.pkg.github.com/hiroaki-yamamoto/midas/<<parameters.service_name>> .
          working_directory: backend
      - run:
          name: Push Docker Image
          command: |
            docker push docker.pkg.github.com/hiroaki-yamamoto/midas/<<parameters.service_name>>
      - slack/notify:
          event: fail
          ignore_errors: false
          template: basic_fail_1
      - run: docker logout https://docker.pkg.github.com
  notify:
    docker:
      - image: ubuntu
        environment:
          BASH_ENV: /etc/profile
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install essential tools"
          command: "apt-get update && apt-get install -y jq curl"
      - run:
          name: "Export slack notification on success"
          command: |
            echo 'export SLACK_TMPL_PASS=$(cat ./.circleci/slack_template_success.json)' >> $BASH_ENV
      - slack/notify:
          event: always
          ignore_errors: false
          template: SLACK_TMPL_PASS

devel-filter: &devel-filter
  filters:
    branches:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - build-backend:
          <<: *devel-filter
      - deploy-image:
          name: "Historical Kline Service Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: historical_service
      - deploy-image:
          name: "Historical Kline Fetch Worker Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: historical_fetch_worker
      - deploy-image:
          name: "Historical Kline Aggregation Worker Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: historical_aggregator
      - deploy-image:
          name: "Historical Kline Record Worker Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: historical_record_worker
      - deploy-image:
          name: "Symbol Service Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: symbol_service
      - deploy-image:
          name: "Trade Observer Worker Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: observer_worker
      - deploy-image:
          name: "Trade Observer Service Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: observer_service
      - deploy-image:
          name: "Keychain Service Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: keychain_service
      - deploy-image:
          name: "Notification Worker Deployment"
          requires:
            - build-backend
          filters:
            branches:
              only: master
          service_name: notify_worker
      - notify:
          name: "Deploy Success Notification"
          filters:
            branches:
              ignore: master
          requires:
            - build-backend
      - notify:
          name: "Deploy Success Notification"
          filters:
            branches:
              only: master
          requires:
            - Historical Kline Service Deployment
            - Historical Kline Fetch Worker Deployment
            - Historical Kline Aggregation Worker Deployment
            - Historical Kline Record Worker Deployment
            - Symbol Service Deployment
            - Trade Observer Worker Deployment
            - Trade Observer Service Deployment
            - Keychain Service Deployment
            - Notification Worker Deployment
