apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "deployment.yml"
  - "svc.yml"

namespace: midas

configMapGenerator:
  - name: nats-config
    files:
      - "nats.conf"
