apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: management
      port: 8222
      targetPort: 8222
    - name: clustering
      port: 6222
      targetPort: 6222
