apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - broker/deployment.yml
  - kvs/deployment.yml
  - database
  - frontend
  - namespace.yml
  - proxy
namespace: midas
secretGenerator:
  - name: proxy-cert
    type: kubernetes.io/tls
    files:
      - ./tls/certs/proxy/tls.crt
      - ./tls/certs/proxy/tls.key
  - name: svc-cert
    type: kubernetes.io/tls
    files:
      - ./tls/certs/svc/tls.crt
      - ./tls/certs/svc/tls.key
  - name: root-key
    files:
      - ./tls/certs/root/root-ca.pem
      - ./tls/certs/root/root-ca.srl
      - ./tls/certs/root/root.key
