apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - broker/deployment.yml
  - kvs/deployment.yml
  - database
  - frontend
  - namespace.yml
  - proxy
namespace: midas
configMapGenerator:
  - name: browser-cert
    files:
      - ./tls/certs/browser.crt
      - ./tls/certs/browser.key
      - ./tls/certs/root-ca.pem
  - name: svc-cert
    files:
      - ./tls/certs/svc.crt
      - ./tls/certs/svc.key
      - ./tls/certs/root-ca.pem
