apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tls
  - broker/deployment.yml
  - kvs/deployment.yml
  - database
  - frontend
  - namespace.yml
  - proxy
  - services
namespace: midas
