apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: ingress
  labels:
    app: midas
spec:
  tls: []
  defaultBackend:
    service:
      name: frontend
      port:
        name: https
