apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: trade-observer

resources:
  - "../../template"

patches:
  - target:
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: trade
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: trade-observer

images:
  - name: template
    newName: trade-observer-service
