apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvs
  labels:
    app: kvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvs
  template:
    metadata:
      labels:
        app: kvs
    spec:
      containers:
        - name: kvs
          image: redis:alpine
          resources:
            requests:
              cpu: 2m
              memory: 1Mi
            limits:
              cpu: 1000m
              memory: 1Gi
