[package]
name = "notify_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }
subscribe = { path = "../../libs/subscribe" }

notification = { path = "../../libs/exchanges/notification" }

clap = { version = "4.4.10", features = ["derive"] }
tokio = { version = "1.34.0", features = ["rt", "rt-multi-thread", "signal"] }
libc = "0.2.150"
futures = "0.3.26"
