[package]
name = "notify_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exchanges = { path = "../../libs/exchanges" }
config = { path = "../../libs/config" }

clap = "3.0.0-beta.2"
tokio = { version = "1.2.0", features = [
  "rt",
  "rt-multi-thread",
  "signal",
]}
nats = "^0.8.0"
libc = "0.2.86"
futures = "0.3.12"
