[package]
name = "notify_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }

notification = { path = "../../libs/exchanges/notification" }

clap = { version = "3.2.14", features = ["derive"] }
tokio = { version = "1.20.0", features = [
  "rt",
  "rt-multi-thread",
  "signal",
] }
nats = "0.22.0"
libc = "0.2.126"
futures = "0.3.21"
