[package]
name = "notify_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }

notification = { path = "../../libs/rulesets/notification" }
binance_notification = { path = "../../libs/exchanges/binance/notification" }

clap = "3.0.0-beta.2"
tokio = { version = "1.7.1", features = [
  "rt",
  "rt-multi-thread",
  "signal",
] }
nats = "0.9.18"
libc = "0.2.97"
futures = "0.3.15"
