[package]
name = "trade_observer_control_worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observers = { path = "../../libs/exchanges/observers" }
symbols = { path = "../../libs/exchanges/symbols" }
kvs = { path = "../../libs/kvs" }
entities = { path = "../../libs/entities" }
config = { path = "../../libs/config" }
subscribe = { path = "../../libs/subscribe" }
errors = { path = "../../libs/errors" }
rpc = { path = "../../libs/rpc" }

tokio = { version = "1.35.0", features = [
  "macros",
  "rt-multi-thread",
  "time",
  "sync",
] }
log = "0.4.20"
futures = "0.3.29"
uuid = { version = "1.6.1", features = ["v4"] }
err-derive = "0.3.1"
num-traits = "0.2.17"
num-derive = "0.4.1"
mongodb = { version = "2.7.1", default-features = false, features = [
  "async-std-runtime",
] }
