[package]
name = "trade_observer_control_worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }

kvs = { path = "../../libs/kvs" }
entities = { path = "../../libs/entities" }
observers = { path = "../../libs/exchanges/observers" }
config = { path = "../../libs/config" }
log = "0.4.19"
