[package]
name = "trade_observer_control_worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvs = { path = "../../libs/kvs" }
entities = { path = "../../libs/entities" }
observers = { path = "../../libs/exchanges/observers" }
config = { path = "../../libs/config" }
subscribe = { path = "../../libs/subscribe" }
errors = { path = "../../libs/errors" }

tokio = { version = "1.30.0", features = [
  "macros",
  "rt-multi-thread",
  "time",
  "sync",
] }
log = "0.4.19"
futures = "0.3.28"
uuid = "1.4.1"
rand = "0.8.5"
err-derive = "0.3.1"
