[package]
name = "keychain_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keychain = { path = "../../libs/keychain" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }

clap = { version = "3.0.5", features = ["derive"] }
mongodb = { version = "2.1.0", default-features = false, features = ["async-std-runtime"] }
tokio = { version = "1.15.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
warp = { version = "0.3.2", features = ["tls"] }
slog = "2.7.0"
futures = "0.3.19"
serde = { version = "1.0.133", features=["derive"] }
libc = "0.2.112"
num-traits = "0.2.14"
http = "0.2.6"
nats = "0.16.0"
