[package]
name = "keychain_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keychain = { path = "../../libs/keychain" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }
access_logger = { path = "../../libs/access_logger" }

clap = { version = "3.2.8", features = ["derive"] }
mongodb = { version = "2.2.2", default-features = false, features = ["async-std-runtime"] }
tokio = { version = "1.19.2", features = ["macros", "rt", "rt-multi-thread", "signal"] }
warp = { version = "0.3.2", features = ["tls"] }
slog = "2.7.0"
futures = "0.3.21"
serde = { version = "1.0.138", features=["derive"] }
libc = "0.2.126"
num-traits = "0.2.15"
http = "0.2.8"
nats = "0.21.0"
