[package]
name = "keychain_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keychain = { path = "../../libs/keychain" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }
access_logger = { path = "../../libs/access_logger" }

clap = { version = "4.0.29", features = ["derive"] }
mongodb = { version = "2.3.1", default-features = false, features = ["async-std-runtime"] }
tokio = { version = "1.22.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
warp = { version = "0.3.3", features = ["tls"] }
log = { version = "0.4", features = [ "kv_unstable", "kv_unstable_serde" ] }
futures = "0.3.25"
serde = { version = "1.0.148", features=["derive"] }
libc = "0.2.138"
num-traits = "0.2.15"
http = "0.2.8"
nats = "0.23.1"
