[package]
name = "keychain_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exchanges = { path = "../../libs/exchanges" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }

clap = "3.0.0-beta.2"
mongodb = {version = "1.2.0", default-features = false, features = ["async-std-runtime"]}
tokio = {version = "1.2", features = ["macros", "rt", "rt-multi-thread", "signal"]}
warp = "0.3"
slog = "2.7.0"
futures = "0.3.13"
serde = "1.0.123"
libc = "0.2.86"
num-traits = "0.2.14"
http = "0.2.3"
nats = "0.8"
