[package]
name = "historical_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../../libs/types" }
exchanges = { path = "../../libs/exchanges" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }

serde = {version = "1.0.119", features = ["derive"]}
rmp-serde = "0.15.1"
nats = "0.8.6"
mongodb = "1.1.1"
clap = "3.0.0-beta.2"
serde_yaml = "0.8.15"
tokio = {version = "1.0", features = ["macros", "rt", "rt-multi-thread", "signal"]}
slog = "2.7.0"
async-stream = "0.3.0"
futures = "0.3.12"
num-traits = "0.2.14"
libc = "0.2.82"
warp = { version = "0.3", features = ["tls"] }
serde_json = "1.0.61"
http = "0.2.3"
