[package]
name = "historical_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

slog_builder = { path = "../../libs/slog_builder" }
types = { path = "../../libs/types" }
exchanges = { path = "../../libs/exchanges" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }

tonic = { version = "0.3.1", features = ["transport", "tls"] }
serde = {version = "1.0.117", features = ["derive"]}
rmp-serde = "0.14.4"
nats = "0.8.2"
mongodb = "1.1.1"
clap = "3.0.0-beta.2"
serde_yaml = "0.8.14"
tokio = {version = "0.3.3", features = ["macros", "rt-threaded", "signal"]}
slog = "2.5.2"
slog-atomic = "3.0.0"
async-stream = "0.3.0"
futures = "0.3.7"
num-traits = "0.2.14"
libc = "0.2.80"
warp = { version = "0.2.5", features = ["tls"] }
serde_json = "1.0.59"
