[package]
name = "historical_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../../libs/types" }
rpc = { path = "../../libs/rpc" }
access_logger = { path = "../../libs/access_logger" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }
subscribe = { path = "../../libs/subscribe" }
errors = { path = "../../libs/errors" }
probe = { path = "../../libs/probe" }

history = { path = "../../libs/exchanges/history" }
entities = { path = "../../libs/entities" }
symbols = { path = "../../libs/exchanges/symbols" }

serde = { version = "1.0.138", features = ["derive"] }
rmp-serde = "1.1.0"
nats = "0.21.0"
mongodb = { version = "2.2.2", default-features = false, features = ["async-std-runtime"] }
clap = { version = "3.2.8", features = ["derive"] }
serde_yaml = "0.8.25"
tokio = { version = "1.19.2", features = ["macros", "rt", "rt-multi-thread", "signal", "sync"] }
slog = "2.7.0"
futures = "0.3.21"
num-traits = "0.2.15"
libc = "0.2.126"
warp = { version = "0.3.2", features = ["tls"] }
serde_json = "1.0.82"
http = "0.2.8"
