[package]
name = "historical_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../../libs/types" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }

history_fetcher = { path = "../../libs/rulesets/history_fetcher" }
binance_histories = { path = "../../libs/exchanges/binance/histories" }
binance_symbols = { path = "../../libs/exchanges/binance/symbols" }

serde = { version = "1.0.124", features = ["derive"] }
rmp-serde = "0.15.4"
nats = "0.8"
mongodb = { version = "1.2.0", default-features = false, features = ["async-std-runtime"] }
clap = "3.0.0-beta.2"
serde_yaml = "0.8.17"
tokio = { version = "1.4.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
slog = "2.7.0"
async-stream = "0.3.0"
futures = "0.3.13"
num-traits = "0.2.14"
libc = "0.2.91"
warp = { version = "0.3.0", features = ["tls"] }
serde_json = "1.0.64"
http = "0.2.3"
