url: https://api.binance.com/api/v1/klines
model: data/lstm.hd5
timeFieldIndex: 0

start: &start 2010-01-01 00:00:00
end: &end null
limit: &limit 1000
epoch: true
timeUnit: 1000

timeFieldName:
  start: startTime
  end: endTime

urlparams:
  symbol: BTCUSDT
  interval: 1d
  limit: *limit

csv:
  fields: [
    "openTime", "open", "high", "low", "close",
    "volume", "closeTime", "asset_vol", "num_trades"
  ]
  out: data/binance-BTCUSDT.csv

splitRate: 0.85
seq: 30
dur: 15
