[package]
name = "trade_observer_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observers = { path = "../../libs/exchanges/observers" }
config = { path = "../../libs/config" }
rpc = { path = "../../libs/rpc" }
csrf = { path = "../../libs/csrf" }
access_logger = { path = "../../libs/access_logger" }
subscribe = { path = "../../libs/subscribe" }
errors = { path = "../../libs/errors" }

futures = "0.3.26"
warp = { version = "0.3.3", features = ["tls"] }
clap = { version = "4.3.0", features = ["derive"] }
log = { version = "0.4", features = ["kv_unstable", "kv_unstable_serde"] }
tokio = { version = "1.25.0", features = [
  "macros",
  "signal",
  "time",
  "rt",
  "rt-multi-thread",
] }
libc = "0.2.139"
mongodb = { version = "2.4.0", default-features = false, features = [
  "async-std-runtime",
] }
serde_json = "1.0.93"
