[package]
name = "trade_observer_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observers = { path = "../../libs/exchanges/observers" }
config = { path = "../../libs/config" }
rpc = { path = "../../libs/rpc" }
csrf = { path = "../../libs/csrf" }
access_logger = { path = "../../libs/access_logger" }

futures = "0.3.24"
nats = "0.23.0"
warp = { version = "0.3.3", features = ["tls"] }
clap = { version = "4.0.10", features = ["derive"] }
slog = "2.7.0"
tokio = { version = "1.21.2", features = ["macros", "signal", "time", "rt", "rt-multi-thread"] }
libc = "0.2.134"
mongodb = { version = "2.3.1", default-features = false, features = ["async-std-runtime"] }
serde_json = "1.0.85"
