[package]
name = "observer_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exchanges = { path = "../../libs/exchanges" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }
slog_builder = { path = "../../libs/slog_builder" }

clap = "3.0.0-beta.2"
tokio = {version = "0.3.3", features = ["signal", "rt-threaded", "macros"]}
nats = "0.8.2"
slog = "2.5.2"
tonic = { version = "0.3.1", features = ["transport", "tls"] }
futures = "0.3.7"
libc = "0.2.80"
