[package]
name = "observer_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance_observers = { path = "../../libs/exchanges/binance/observers" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }

clap = "3.0.0-beta.5"
tokio = { version = "1.14.0", features = ["signal", "rt", "rt-multi-thread", "macros"] }
nats = "0.16.0"
slog = "2.7.0"
futures = "0.3.17"
libc = "0.2.108"
mongodb = { version = "2.0.2", default-features = false, features = ["async-std-runtime"] }
