[package]
name = "observer_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance_observers = { path = "../../libs/exchanges/binance/observers" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }

clap = "3.0.0-beta.2"
tokio = { version = "1.6.0", features = ["signal", "rt", "rt-multi-thread", "macros"] }
nats = "0.9.16"
slog = "2.7.0"
futures = "0.3.15"
libc = "0.2.94"
mongodb = { version = "1.2.1", default-features = false, features = ["async-std-runtime"] }
