[package]
name = "observer_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exchanges = { path = "../../libs/exchanges" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }

clap = "3.0.0-beta.2"
tokio = {version = "0.2.23", features = ["signal", "rt-threaded", "macros"]}
nats = "0.8.6"
slog = "2.5.2"
futures = "0.3.8"
libc = "0.2.80"
