[package]
name = "observer_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observers = { path = "../../libs/exchanges/observers" }
rpc = { path = "../../libs/rpc" }
config = { path = "../../libs/config" }

clap = { version = "3.0.14", features = ["derive"] }
tokio = { version = "1.16.1", features = ["signal", "rt", "rt-multi-thread", "macros"] }
nats = "0.17.0"
slog = "2.7.0"
futures = "0.3.21"
libc = "0.2.117"
mongodb = { version = "2.1.0", default-features = false, features = ["async-std-runtime"] }
