[package]
name = "bot_workers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.1", features = ["macros", "rt", "rt-multi-thread", "signal"] }

[[bin]]
name = "bot_manager_worker"
path = "./src/bot_manager_worker.rs"

[[bin]]
name = "bot_worker"
path = "./src/bot_worker.rs"
