[package]
name = "symbol_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../../libs/rpc" }
symbols = { path = "../../libs/exchanges/symbols" }
types = { path = "../../libs/types" }
errors = { path = "../../libs/errors" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }
access_logger = { path = "../../libs/access_logger" }
probe = { path = "../../libs/probe" }

mongodb = { version = "2.3.0", default-features = false, features = ["async-std-runtime"] }
slog = "2.7.0"
clap = { version = "3.2.16", features = ["derive"] }
tokio = { version = "1.20.1", features = ["macros", "rt", "rt-multi-thread", "signal"] }
futures = "0.3.21"
libc = "0.2.126"
nats = "0.22.0"
warp = { version = "0.3.2", features = ["tls"] }
num-traits = "0.2.15"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
