[package]
name = "symbol_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../../libs/rpc" }
exchanges = { path = "../../libs/exchanges" }
types = { path = "../../libs/types" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }

mongodb = "1.1.1"
slog = "2.7.0"
clap = "3.0.0-beta.2"
tokio = {version = "0.2.24", features = ["macros", "rt-threaded", "signal"]}
futures = "0.3.8"
libc = "0.2.81"
nats = "0.8.6"
warp = "0.2.5"
num-traits = "0.2.14"
