[package]
name = "symbol_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../../libs/rpc" }
binance_symbols = { path = "../../libs/exchanges/binance/symbols" }
types = { path = "../../libs/types" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }

mongodb = { version = "1.2.0", default-features = false, features = ["async-std-runtime"] }
slog = "2.7.0"
clap = "3.0.0-beta.2"
tokio = { version = "1.3.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
futures = "0.3.13"
libc = "0.2.88"
nats = "0.8"
warp = { version = "0.3.0", features = ["tls"] }
num-traits = "0.2.14"
