[package]
name = "symbol"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../../libs/rpc" }
exchanges = { path = "../../libs/exchanges" }
types = { path = "../../libs/types" }
config = { path = "../../libs/config" }
slog_builder = { path = "../../libs/slog_builder" }

tonic = { version =  "0.3.1", features = ["transport", "tls"] }
mongodb = "1.1.1"
slog = "2.5.2"
num-traits = "0.2.12"
clap = "3.0.0-beta.1"
tokio = {version = "0.2.22", features = ["macros", "rt-threaded", "signal"]}
futures = "0.3.5"
libc = "0.2.76"
