[package]
name = "symbol_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../../libs/rpc" }
symbols = { path = "../../libs/exchanges/symbols" }
types = { path = "../../libs/types" }
errors = { path = "../../libs/errors" }
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }
access_logger = { path = "../../libs/access_logger" }
subscribe = { path = "../../libs/subscribe" }

mongodb = { version = "2.4.0", default-features = false, features = [
  "async-std-runtime",
] }
log = { version = "0.4", features = ["kv_unstable", "kv_unstable_serde"] }
clap = { version = "4.3.0", features = ["derive"] }
tokio = { version = "1.25.0", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "signal",
] }
futures = "0.3.26"
libc = "0.2.139"
warp = { version = "0.3.3", features = ["tls"] }
num-traits = "0.2.15"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
