[package]
name = "symbol"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../../libs/rpc" }
exchanges = { path = "../../libs/exchanges" }
types = { path = "../../libs/types" }

tonic = "0.3.1"
mongodb = "1.1.0"
slog = "2.5.2"
num-traits = "0.2.12"
