[package]
name = "observer_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exchanges = { path = "../../libs/exchanges" }
config = { path = "../../libs/config" }
rpc = { path = "../../libs/rpc" }
csrf = { path = "../../libs/csrf" }

futures = "0.3.12"
nats = "0.8.6"
warp = "0.3"
clap = "3.0.0-beta.2"
slog = "2.7.0"
tokio = { version = "1.0", features = ["macros", "signal", "time"] }
libc = "0.2.82"
mongodb = "1.1.1"
rmp-serde = "0.15.1"
