[package]
name = "observer_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance_observers = { path = "../../libs/exchanges/binance/observers" }
config = { path = "../../libs/config" }
rpc = { path = "../../libs/rpc" }
csrf = { path = "../../libs/csrf" }

futures = "0.3.13"
nats = "0.8"
warp = { version = "0.3.0", features = ["tls"] }
clap = "3.0.0-beta.2"
slog = "2.7.0"
tokio = { version = "1.3.0", features = ["macros", "signal", "time", "rt", "rt-multi-thread"] }
libc = "0.2.88"
mongodb = { version = "1.2.0", default-features = false, features = ["async-std-runtime"] }
rmp-serde = "0.15.4"
