[package]
name = "observer_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observers = { path = "../../libs/exchanges/observers" }
config = { path = "../../libs/config" }
rpc = { path = "../../libs/rpc" }
csrf = { path = "../../libs/csrf" }

futures = "0.3.21"
nats = "0.18.1"
warp = { version = "0.3.2", features = ["tls"] }
clap = { version = "3.1.8", features = ["derive"] }
slog = "2.7.0"
tokio = { version = "1.17.0", features = ["macros", "signal", "time", "rt", "rt-multi-thread"] }
libc = "0.2.121"
mongodb = { version = "2.1.0", default-features = false, features = ["async-std-runtime"] }
serde_json = "1.0.79"
