[package]
name = "observer"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exchanges = { path = "../../libs/exchanges" }
config = { path = "../../libs/config" }
rpc = { path = "../../libs/rpc" }
types = { path = "../../libs/types" }

futures = "0.3.7"
nats = "0.8.3"
warp = "0.2.5"
clap = "3.0.0-beta.2"
slog = "2.5.2"
tokio = { version = "0.2.22", features = ["macros", "signal"] }
serde_json = "1.0.59"
libc = "0.2.80"
