[package]
name = "observer_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance_observers = { path = "../../libs/exchanges/binance/observers" }
config = { path = "../../libs/config" }
rpc = { path = "../../libs/rpc" }
csrf = { path = "../../libs/csrf" }

futures = "0.3.18"
nats = "0.16.0"
warp = { version = "0.3.2", features = ["tls"] }
clap = { version = "3.0.0-rc.4", features = ["derive"] }
slog = "2.7.0"
tokio = { version = "1.14.0", features = ["macros", "signal", "time", "rt", "rt-multi-thread"] }
libc = "0.2.112"
mongodb = { version = "2.0.2", default-features = false, features = ["async-std-runtime"] }
serde_json = "1.0.73"
