[package]
name = "token_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }
access_logger = { path = "../../libs/access_logger" }
rpc = { path = "../../libs/rpc" }

slog = "2.7.0"
clap = { version = "3.1.9", features = ["derive"] }
tokio = { version = "1.17.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
futures = "0.3.21"
libc = "0.2.123"
warp = { version = "0.3.2", features = ["tls"] }
