[package]
name = "token_service"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }
csrf = { path = "../../libs/csrf" }

slog = "2.7.0"
clap = "3.0.0-beta.2"
tokio = { version = "1.4.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
futures = "0.3.13"
libc = "0.2.93"
warp = { version = "0.3.1", features = ["tls"] }
