[package]
name = "historical_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

[[bin]]
name = "historical_fetch_worker"
path = "./src/main_fetcher.rs"

[[bin]]
name = "historical_date_splitter"
path = "./src/main_splitter.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }
types = { path = "../../libs/types" }
rpc = { path = "../../libs/rpc" }

subscribe = { path = "../../libs/subscribe" }

history = { path = "../../libs/exchanges/history" }
symbols = { path = "../../libs/exchanges/symbols" }

slog = "2.7.0"
tokio = { version = "1.13.0", features = ["rt", "rt-multi-thread", "macros", "signal"] }
nats = "0.16.0"
clap = "3.0.0-beta.5"
mongodb = { version = "2.0.1", default-features = false, features = ["async-std-runtime"] }
futures = "0.3.17"
libc = "0.2.107"
tokio-stream = "0.1.8"
