[package]
name = "historical-workers"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }
exchanges = { path = "../../libs/exchanges" }
slog_builder = { path = "../../libs/slog_builder" }
types = { path = "../../libs/types" }

slog = "2.5.2"
nats = "0.8.0"
tokio = { version = "0.2.22", features = ["rt-threaded", "macros", "signal"] }
clap = "3.0.0-beta.2"
mongodb = "1.1.1"
futures = "0.3.5"
libc = "0.2.77"

[[bin]]
name = "historical_fetch_worker"
path = "src/historical_fetcher.rs"

[[bin]]
name = "historical_record_worker"
path = "src/historical_recorder.rs"
