[package]
name = "historical_worker"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2021"

[[bin]]
name = "historical_fetch_worker"
path = "./src/main_fetcher.rs"

[[bin]]
name = "historical_date_splitter"
path = "./src/main_splitter.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }
types = { path = "../../libs/types" }
rpc = { path = "../../libs/rpc" }

subscribe = { path = "../../libs/subscribe" }

history = { path = "../../libs/exchanges/history" }
symbols = { path = "../../libs/exchanges/symbols" }
date_splitter = { path = "../../libs/date_splitter" }

slog = "2.7.0"
tokio = { version = "1.20.1", features = ["rt", "rt-multi-thread", "macros", "signal"] }
nats = "0.23.0"
clap = { version = "3.2.17", features = ["derive"] }
mongodb = { version = "2.3.0", default-features = false, features = ["async-std-runtime"] }
futures = "0.3.23"
libc = "0.2.131"
