[package]
name = "historical-workers"
version = "0.1.0"
authors = ["Hiroaki Yamamoto <hiroaki@hysoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../libs/config" }
types = { path = "../../libs/types" }
rpc = { path = "../../libs/rpc" }

history = { path = "../../libs/rulesets/history" }

binance_histories = { path = "../../libs/exchanges/binance/histories" }
binance_symbols = { path = "../../libs/exchanges/binance/symbols" }

slog = "2.7.0"
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros", "signal"] }
nats = "0.9.8"
clap = "3.0.0-beta.2"
mongodb = "1.2.0"
futures = "0.3.13"
libc = "0.2.91"

[[bin]]
name = "historical_fetch_worker"
path = "src/main_fetcher.rs"

[[bin]]
name = "historical_record_worker"
path = "src/main_recorder.rs"

[[bin]]
name = "historical_aggregator"
path = "src/main_aggregator.rs"
