name: Rust

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./backend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust x86_64-unknown-linux-musl components
      run: rustup target add x86_64-unknown-linux-musl
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl
