name: "Build Backend"
on:
  push:
    branches:
      - '**'
jobs:
  build-access-logger:
    uses: "hiroaki-yamamoto/midas/.github/workflows/build-backend-libs-template.yml@master"
    with:
      pkgid: "access_logger"
