name: "Build Backend"
on:
  push:
    branches:
      - '**'
jobs:
  build-access-logger:
    - name: "Build Access Logger"
      uses: "hiroaki-yamamoto/midas/.github/workflows/build-backend-libs-template.yml@master"
      with:
        pkgid: "access_logger"
