name: Delete docker package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: historical
